title: Hello, world!
description: Carl Ekman - iOS developer and app designer in Stockholm, Sweden.
# theme: no-theme
markdown: kramdown
google_analytics: UA-104149000-1
social:
  email: hello@carlekman.com
  github: CarlEkman
  twitter: carlekman
  dribbble: CarlEkman
  linkedin: carljuliusekman
